version: '3.9'

services:
  tours:
    build:
      dockerfile: Dockerfile
      context: ./tours
    image: microservice-tours:improve1
    container_name: tours-container
    restart: always
    networks:
      - servers
    ports:
      - "88:88"
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: soa_tours
      PGSEARCHPATH: tours
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-data:
    name: tours-database-data

networks:
  servers:
    name: servers
    driver: bridge